export const DEFAULT_LANGUAGE = { key: "eng", value: "English" };

export const LANGUAGES = [
  { key: "afr", value: "Afrikaans" },
  { key: "amh", value: "Amharic" },
  { key: "ara", value: "Arabic" },
  { key: "asm", value: "Assamese" },
  { key: "aze", value: "Azerbaijani" },
  { key: "aze_cyrl", value: "Azerbaijani - Cyrillic" },
  { key: "bel", value: "Belarusian" },
  { key: "ben", value: "Bengali" },
  { key: "bod", value: "Tibetan" },
  { key: "bos", value: "Bosnian" },
  { key: "bul", value: "Bulgarian" },
  { key: "cat", value: "Catalan; Valencian" },
  { key: "ceb", value: "Cebuano" },
  { key: "ces", value: "Czech" },
  { key: "chi_sim", value: "Chinese - Simplified" },
  { key: "chi_tra", value: "Chinese - Traditional" },
  { key: "chr", value: "Cherokee" },
  { key: "cym", value: "Welsh" },
  { key: "dan", value: "Danish" },
  { key: "deu", value: "German" },
  { key: "dzo", value: "Dzongkha" },
  { key: "ell", value: "Greek, Modern (1453-)" },
  { key: "eng", value: "English" },
  { key: "epo", value: "Esperanto" },
  { key: "est", value: "Estonian" },
  { key: "fin", value: "Finnish" },
  { key: "fra", value: "French" },
  { key: "gle", value: "Irish" },
  { key: "hat", value: "Haitian; Haitian Creole" },
  { key: "heb", value: "Hebrew" },
  { key: "hin", value: "Hindi" },
  { key: "hun", value: "Hungarian" },
  { key: "ind", value: "Indonesian" },
  { key: "isl", value: "Italian" },
  { key: "jpn", value: "Japanese" },
  { key: "kat", value: "Georgian" },
  { key: "kor", value: "Korean" },
  { key: "kur", value: "Kurdish" },
  { key: "lao", value: "Lao" },
  { key: "lat", value: "Latvian" },
  { key: "lit", value: "Lithuanian" },
  { key: "mal", value: "Malayalam" },
  { key: "mkd", value: "Macedonian" },
  { key: "mlt", value: "Maltese" },
  { key: "mya", value: "Burmese" },
  { key: "nep", value: "Nepali" },
  { key: "nor", value: "Norwegian" },
  { key: "pol", value: "Polish" },
  { key: "por", value: "Portuguese" },
  { key: "ron", value: "Romanian; Moldavian" },
  { key: "rus", value: "Russian" },
  { key: "san", value: "Sanskrit" },
  { key: "slk", value: "Slovak" },
  { key: "slv", value: "Slovenian" },
  { key: "spa", value: "Spanish; Castilian" },
  { key: "srp", value: "Serbian" },
  { key: "srp_latn", value: "Serbian - Latin" },
  { key: "swa", value: "Swahili" },
  { key: "swe", value: "Swedish" },
  { key: "syr", value: "Syriac" },
  { key: "tur", value: "Turkish" },
  { key: "tha", value: "Thai" },
  { key: "ukr", value: "Ukrainian" },
  { key: "uzb", value: "Uzbek" },
  { key: "uzb_cyrl", value: "Uzbek - Cyrillic" },
  { key: "vie", value: "Vietnamese" },
  { key: "yid", value: "Yiddish" },
];
